### ISSUE TITLE
Error downloading artifact from GitHub - Http Status 400

### ISSUE THREAD

**Issue by cleuton** [cleuton/jqana#16]
Recently GitHub has changed its API and we can no longer deploy maven artifacts to it. We are trying some workarounds. Meanwhile, you can download the jQana JAR file and use "mvn install:file" to install in your own repository, or you can build it. 

https://raw.githubusercontent.com/cleuton/jqana/mvn-repo/com/obomprogramador/tools/jqana-maven-plugin/0.0.6/jqana-maven-plugin-0.0.6.jar

**Comment by XP1** [comment]
1) Fork the project.
2) Click on the Settings tab: https://github.com/%username%/jqana/settings
3) Under "GitHub Pages", select "master branch".
4) Click "Save".
5) Open the "mvn-repo" branch: https://github.com/cleuton/jqana/tree/mvn-repo
6) Click "Clone or download".
7) Click "Download ZIP".
8) Extract the ZIP file into the master branch.
9) Rename folder to "mvn-repo".
10) Push changes to repo.
11) Use the following repository in POM file: [https://%username%.github.io/jqana/mvn-repo/](https://%username%.github.io/jqana/mvn-repo/)

`pom.xml`:

    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        ...

        <pluginRepositories>
            <pluginRepository>
                <id>jqana-mvn-repo</id>
                <url>https://%username%.github.io/jqana/mvn-repo/</url>
            </pluginRepository>
        </pluginRepositories>

        <reporting>
            <plugins>
                <plugin>
                    <groupId>com.obomprogramador.tools</groupId>
                    <artifactId>jqana-maven-plugin</artifactId>
                    <version>0.0.6</version>
                </plugin>
            </plugins>
        </reporting>
    </project>

**Comment by cleuton** [comment]
jQana will be refactored. Component is no longer working. We are working on a new version.
