### ISSUE TITLE
Quando teremos uma nova versão do plugin jqana

### ISSUE THREAD

**Issue by tacianosilva** [cleuton/jqana#17]
Olá @cleuton,

Gostei das métricas do jqana e gostaria de saber quando teremos novas versões e funcionalidades na ferramenta de cálculos de métricas?

Att,
Taciano

**Comment by cleuton** [comment]
Estou procurando colaboradores. Como tenho vários projetos, fica difícil tocar tudo sozinho.

**Comment by tacianosilva** [comment]
Sei como é!
Também tenho pouco tempo, mas gostaria de contribuir de alguma forma!
Farei um fork do jqana e quando tiver um tempinho vou dar uma olhada.
[]'s

**Comment by cleuton** [comment]
ótimo!

o futuro é o jqana-control. veja no bom programador

**Comment by tacianosilva** [comment]
Ok! Vou dar uma olhada!
